name: remedi_auth
description: Remedi Plugin Auth
version: 0.0.1
author:
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  #svg loader
  flutter_svg: ^0.19.1

  # store access token
  # flutter_secure_storage: ^3.3.5

  # kakao login
  flutter_kakao_login: ^3.1.0

  # sign in with apple
  sign_in_with_apple: ^3.0.0

  #basic architecture of app
  stacked_mvvm:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      path: stacked_mvvm/

  remedi_widgets:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      path: remedi_widgets/

  remedi_base:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      path: remedi_base/

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
