name: remedi_auth
description: Remedi Plugin Auth
version: 2.0.0
author:
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #svg loader
  flutter_svg: ^0.22.0

  # kakao login
  flutter_kakao_login: ^3.3.0

  # sign in with apple
  sign_in_with_apple: ^3.0.0

  # phone verification
  firebase_auth: ^3.0.1

  # phone number input.
  #  flutter_libphonenumber: ^1.0.4
  #  flutter_multi_formatter: ^2.2.0
  expandable: ^5.0.1

  libphonenumber_plugin: ^0.2.3
  equatable: ^2.0.0
  collection: ^1.15.0

  #basic architecture of app
  stacked_mvvm:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter_app_components.git
      ref: null-safety
      path: stacked_mvvm/

  remedi_widgets:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter_app_components.git
      ref: null-safety
      path: remedi_widgets/

  remedi_base:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter_app_components.git
      ref: null-safety
      path: remedi_base/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
