name: remedi_auth
description: Remedi Plugin Auth
version: 2.0.0
author:
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #svg loader
  flutter_svg: ^0.22.0

  # kakao login
  flutter_kakao_login: ^3.2.1

  # sign in with apple
  sign_in_with_apple: ^3.0.0

  # phone verification
  firebase_auth: ^1.1.2

  # phone number input.
  flutter_multi_formatter: ^2.0.3

  #basic architecture of app
  stacked_mvvm:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      ref: achoo/0.1.0
      path: stacked_mvvm/

  remedi_widgets:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      ref: achoo/0.1.0
      path: remedi_widgets/

  remedi_base:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      ref: achoo/0.1.0
      path: remedi_base/

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
