name: remedi_flutter
description: Support MVVM architecture using provider.
version: 0.0.2
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  ## [START] architecture
  provider: ^6.0.2
  ## [END] architecture

  ## [START] http api.
  dio: ^4.0.4
  ## [END] http api.

  ## [START] firebase support
  firebase_core: ^1.13.1
  ## [END] firebase support

  ## [START] firebase messaging
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  ## [END] firebase messaging

  ## [START] deep_link
  flutter_branch_sdk: ^5.0.0
  ## [END] deep_link

  # network image
  flutter_svg: ^1.0.0
  extended_image: ^6.0.1
  ## [END] widgets

  ## [START] auth
  # kakao login
  kakao_flutter_sdk: ^1.1.1
  flutterfire_ui: ^0.4.1
  ## [END] auth

  ## [START] permission
  flutter_secure_storage: ^5.0.2
  permission_handler: ^9.2.0
  notification_permissions: ^0.6.1
  ## [END] permission

  ## [START] update
  # go to store on force update page
  store_redirect: ^2.0.0
  ## [END] update

  sembast: ^3.2.0

  ## Crash Monitoring
  firebase_crashlytics: ^2.6.3

  ## Firebase Analytics
  firebase_analytics: ^9.1.7

  # app version, build number and etc
  package_info_plus: ^1.4.0

  # device info, os version, os type
  device_info_plus: ^3.2.2

  firebase_app_installations: ^0.1.0+12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  http_mock_adapter: ^0.3.2

flutter:

