name: example
description: Demonstrates how to use the remedi_base plugin.

version: 0.0.1+1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^2.1.1
  remedi_base:
    path: ../
  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true