name: remedi_base
description: base component.
version: 0.0.5
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # network api.
  dio: ^4.0.4

  # app version, build number and etc
  package_info: ^2.0.2

  # device info, os version, os type
  device_info: ^2.0.3

  # uuid generator
  flutter_udid: ^2.0.0

  # user-agent info.
  # flutter_user_agentx: ^1.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

