name: stacked_mvvm
description: MVVM architecture implementation
version: 2.0.0
author:
homepage:

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0
  stacked: ^2.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
