name: stacked_mvvm
description: MVVM architecture implementation
version: 2.1.0
author:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:

  flutter:
    sdk: flutter

  rxdart: ^0.27.1
  equatable: ^2.0.3
  stacked: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
