name: stacked_mvvm
description: MVVM architecture implementation
version: 1.0.0
author:
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.0
  stacked: ^1.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
