name: stacked_mvvm
description: MVVM architecture implementation
version: 0.0.3
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:

  flutter:
    sdk: flutter

  rxdart: ^0.27.1
  equatable: ^2.0.3
  stacked: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
