name: remedi_analytics
description: A new Flutter package.
version: 0.0.4
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_analytics: ^9.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
