name: multiscreen
description: Support multiscreen(different resolution and size of display) for mobile application.
version: 2.0.0

publish_to: 'none'

flutter:
  plugin:
    platforms:
      android:
        package: me.tossy.flutter.multiscreen
        pluginClass: MultiscreenPlugin
      ios:
        pluginClass: MultiscreenPlugin

environment:
  sdk: ">=2.12.2 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
