name: remedi_splash
description: Splash job module
version: 0.2.0
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  remedi:


  #svg loader
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  remedi:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter_app_components
      path: remedi
      ref: dev

flutter:
