name: remedi_splash
description: A new Flutter package.
version: 0.0.4
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter


  stacked_mvvm: ^0.0.6

  remedi_base: ^0.0.3

  #svg loader
  flutter_svg: ^0.23.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
