name: remedi_splash
description: Splash job module
version: 0.1.1
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'


environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  stacked_mvvm: ^0.0.8

  remedi_base: ^0.0.5

  #svg loader
  flutter_svg: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
