name: remedi_update
description: A new Flutter project.
version: 0.0.1
author:
homepage:

publish_to : 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #basic architecture of app
  stacked_mvvm:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      path: stacked_mvvm/

  remedi_widgets:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      path: remedi_widgets/

  # go to store on force update page
  store_redirect: ^1.0.2

  #svg loader
  flutter_svg: ^0.19.1

  # multi-resolution support.
  multiscreen: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

