name: remedi_update
description: force_update
version: 0.0.2
homepage: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'
repository: 'https://github.com/studio-b-co-kr/remedi_flutter_app_components'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #basic architecture of app
  stacked_mvvm: ^0.0.5

  remedi_widgets: ^0.0.2

  # go to store on force update page
  store_redirect: ^2.0.0

  #svg loader
  flutter_svg: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

