name: remedi_update
description: A new Flutter project.
version: 2.0.0
author:
homepage:

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  #basic architecture of app
  stacked_mvvm:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      ref: achoo-release-0.1.0
      path: stacked_mvvm/

  remedi_widgets:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      ref: achoo-release-0.1.0
      path: remedi_widgets/

  # go to store on force update page
  store_redirect:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter_plugin_mirror.git
      ref: master
      path: store_redirect/

  #svg loader
  flutter_svg: ^0.22.0

  # multi-resolution support.
  multiscreen:
    git:
      url: https://github.com/studio-b-co-kr/remedi_flutter.git
      ref: achoo-release-0.1.0
      path: multiscreen/

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

